# Generated by Django 3.2.9 on 2021-11-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0004_userbmi_bmr'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbmi',
            name='bmi',
            field=models.FloatField(null=True),
        ),
    ]
