# Generated by Django 3.2.9 on 2021-11-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diet', '0007_alter_userbmi_tingkat_aktivitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='jenis',
            field=models.CharField(choices=[('Lauk Hewani', 'Lauk Hewani'), ('Lauk Nabati', 'Lauk Nabati'), ('Sayur', 'Sayur'), ('Nasi', 'Nasi')], max_length=250),
        ),
    ]
